config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :employees
  
  namespace :reports do
    get 'payroll' => 'payroll#show'
  end
  
  scope module: 'ticket' do
    get 'tickets/finalized' => 'tickets#index_finalized'
    resources :tickets do
      
      get 'job' => 'job#index'
      patch 'job' => 'job#update'

      get 'crew-chief' => 'job#index_crew_chief'
      patch 'crew-chief' => 'job#update'
      
      get 'employees' => 'employees#index'
      get 'employees/add' => 'employees#new'
      post 'employees/add' => 'employees#create'
      get 'employees/:employee_id' => 'employees#show', as: :employee_log
      patch 'employees/:employee_id/per-diem' => 'employees#per_diem_toggle', as: :employee_per_diem
      #post 'employees/:employee_id/:status' => 'employees#create_status', as: :employee_new_status
      post 'employees/status' => 'employees#create_status', as: :employee_new_status
      get 'employees/:employee_id/edit/:employee_entry_id' => 'employees#edit_status', as: :employee_edit_status
      patch 'employees/:employee_id/edit/:employee_entry_id' => 'employees#update_status'
      delete 'employees/:employee_id/edit/:employee_entry_id' => 'employees#delete_status'

      get 'vehicles' => 'vehicles#index'
      get 'vehicles/add' => 'vehicles#new'
      post 'vehicles/add' => 'vehicles#create'
      get 'vehicles/:vehicle_id' => 'vehicles#show', as: :vehicle_log
      get 'vehicles/:vehicle_id/inspection' => 'vehicles#display_inspection_form', as: :inspection_form
      get 'vehicles/:vehicle_id/refuel' => 'vehicles#new_refuel', as: :vehicle_refuel
      post 'vehicles/:vehicle_id/refuel' => 'vehicles#create_refuel'
      #post 'vehicles/:vehicle_id/:status' => 'vehicles#create_status', as: :vehicle_new_status
      post 'vehicles/status' => 'vehicles#create_status', as: :vehicle_new_status
      get 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#edit_status', as: :vehicle_edit_status
      patch 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#update_status'
      delete 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#delete_status'
      
      get 'dimensions' => 'dimensions#index'
      patch 'dimensions' => 'dimensions#update'
      
      get 'supplies' => 'supplies#index'
      patch 'supplies' => 'supplies#update'
      
      get 'delays' => 'delays#index'
      patch 'delays' => 'delays#update'
      
      get 'notes' => 'notes#index'
      get 'notes/add' => 'notes#new'
      post 'notes' => 'notes#create'
      
      get 'approval' => 'approval#index'
      get 'approval/:decision' => 'approval#approval_confirm', as: :approval_confirm
      patch 'approval/:decision' => 'approval#update'
      
      
      get 'finalize' => 'finalize#index'
      patch 'finalize' => 'finalize#update'
      
      collection do
        get :autocomplete_job_display_name
        
        get :autocomplete_vehicle_display_name
        
        #get :autocomplete_employee_display_name
        
        get 'autocomplete_crew_chief_display_name' => 'job#autocomplete_employee_display_name'
        
        get 'autocomplete_worker_display_name' => 'employees#autocomplete_employee_display_name'
      end
    end
  end

  
  namespace :admin do
    resources :payroll
    post 'payroll/calculate' => 'payroll#add_pending_tickets', as: :payroll_calculate
    resources :customers
    resources :employees
    resources :vehicles
    resources :jobs do
      get :autocomplete_customer_name, on: :collection
    end
    
    get 'approval/approved' => 'approval#index_approved'
    resources :approval do
      patch :approve
    end
  end
  
  root 'application#homepage'

end

app/controllers/admin/approval_controller.rb
class Admin::ApprovalController < Admin::BaseController
  before_action :set_ticket, only: [:show, :approve]
  decorates_assigned :ticket
  
  def index
    @tickets_pending_approval = Ticket::Ticket.finalized.pending_admin_approval.decorate
    @tickets_approved = Ticket::Ticket.admin_approved.decorate
  end
  
  def index_approved
    index
  end
  
  def show
    
  end
  
  def approve
    @ticket.admin_approved!
    redirect_to admin_approval_index_path
  end
  
  private
    
    # Look up @ticket from params
    def set_ticket
      @ticket = Ticket::Ticket.find(params[:ticket_id] || params[:approval_id] || params[:id])
    end
end

app/controllers/ticket/approval_controller.rb
class Ticket::ApprovalController < Ticket::BaseController
  # Crew chief has tapped Approval in the sidebar
  def index
    if @ticket.pending_approval?
      # Show customer's representative the approval workflow
      approval
    else
      # Show crew chief details of customer approval
      results
    end
  end
  
  # Page 1 of customer screen
  def approval
    @minimal_ui = true
    render :approval
  end
  
  # Page 2 of customer screen
  # Customer has pressed yes or no, and is presented with signature capture
  def approval_confirm
    @minimal_ui = true
    
    case params[:decision]
    when 'approve'
      render :confirm_approve
    when 'disapprove'
      render :confirm_disapprove
    else
      raise
    end
  end
  
  def results
    respond_to do |format|
      
      format.html do
        render :results
      end
      
      format.pdf do
        render pdf: "results",
          template: 'ticket/approval/results'
      end
    end
  end
  
  # Customer has submitted form to finalize approval/disapproval
  def update
    @ticket.approved_at = Time.now
    
    if @ticket.update(ticket_params)
      
      # Add customer feedback to Notes
      if @ticket.approval_feedback.present?
        @ticket.notes.create(
          note_type: :from_customer,
          note: @ticket.approval_feedback
        )
      end
      
      # Email approval
      Ticket::CustomerMailer.ticket_approval_email(@ticket).deliver_later
      
      message = if @ticket.approved?
        'Thanks for approving our work.'
      else
        'Thank you for your feedback.'
      end
      message += " A confirmation will be emailed to #{@ticket.approval_email}."
      
      redirect_to ticket_approval_path, notice: message
    else
      approval_confirm
    end
  end
end

app/helpers/ticket/approval_helper.rb
module Ticket::ApprovalHelper
end

app/views/admin/approval/_index_table.html.slim
- admin_approved = tickets.first and tickets.first.admin_approved?

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th
          | Ticket
        th
          | Employees
        th
          | Square Yards
        th
          | Delays
        th
          | Customer Approval
        th
          | Finalized At
    tbody
      - tickets.each do | ticket |
        tr data-link="#{admin_approval_path(ticket)}"
          td
            strong
              | Ticket #
              = ticket.number
            |  (
            = ticket.crew_chief
            | )
            br
            = ticket.bill_to_pretty
          td
            strong
              = ticket.employees.count
              |  employees
            br
            | Avg: 
            = ticket.employees_summary
          td
            = ticket.milling_square_yards :abbreviate
          td
            = ticket.delays_total :abbreviate
          td
            = ticket.approval
          td
            = ticket.finalized_at

app/views/admin/approval/_table_employees_approval.html.slim
- employees = ticket.employees.decorate
- just_one = employees.count == 1

- if employees.blank?
  | None
- else
  .table-responsive
    table.table.table-striped
      thead
        tr
          - unless just_one
            th
          th Employee
          th On the Job
          th Transport
          th Maintenance
          th Total
          th Per Diem
      tbody
        - employees.each_with_index do | employee, index |
          tr
            - unless just_one
              td
                = index + 1
            td
              = employee.display_name
            td
              = employee.hours_pretty[:on_the_job]
            td
              = employee.hours_pretty[:transport]
            td
              = employee.hours_pretty[:maintenance]
            td
              strong = employee.hours_pretty[:total]
            td
              strong = 'Yes' if employee.per_diem
        - unless just_one
          tr
            th
            th
            th
              = ticket.employee_hours_pretty[:on_the_job]
            th
              = ticket.employee_hours_pretty[:transport]
            th
              = ticket.employee_hours_pretty[:maintenance]
            th
              strong = ticket.employee_hours_pretty[:total]
            th
              = ticket.employees.where(per_diem: true).count

app/views/admin/approval/_table_mills_approval.html.slim
- mills = ticket.mills.decorate
- just_one = mills.count == 1

- if mills.blank?
  | None
- else
  .table-responsive
    table.table.table-striped
      thead
        tr
          - unless just_one
            th
          th Mill
          th On the Job
          th Maintenance
          th Total
      tbody
        - mills.each_with_index do | mill, index |
          tr
            - unless just_one
              td
                = index + 1
            td
              = mill.display_name
            td
              = mill.hours_pretty[:on_the_job]
            td
              = mill.hours_pretty[:maintenance]
            td
              strong = mill.hours_pretty[:total]
        - unless just_one
          tr
            th
            th
            th
              = ticket.mill_hours_pretty[:on_the_job]
            th
              = ticket.mill_hours_pretty[:maintenance]
            th
              strong = ticket.mill_hours_pretty[:total]

app/views/admin/approval/_table_nonmills_approval.html.slim
- nonmills = ticket.nonmills
- just_one = nonmills.count == 1

- if nonmills.blank?
  | None
- else
  .table-responsive
    table.table.table-striped
      thead
        tr
          - unless just_one
            th
          th Vehicle
          th On the Job (Total)
          th Fuel Used
          /th Total
      tbody
        - nonmills.each_with_index do | nonmill, index |
          - nonmill = nonmill.decorate
          tr
            - unless just_one
              td
                = index + 1
            td
              = nonmill.display_name
            td
              = nonmill.hours_pretty[:on_the_job]
            /td
            /  strong = nonmill.hours_pretty[:total]
            td
              = nonmill.fuel_gallons_total
        - unless just_one
          tr
            th
            th
            th
              = ticket.nonmill_hours_pretty[:on_the_job]
            / th
            /   strong = ticket.nonmill_hours_pretty[:total]

app/views/admin/approval/index.html.slim
.page-header
  h1
    | Tickets Pending Approval

= render 'index_table', tickets: @tickets_pending_approval

- if @tickets_approved.present?
  = link_to "Show #{pluralize @tickets_approved.count, 'approved tickets'}", admin_approval_approved_path

app/views/admin/approval/index_approved.html.slim
.page-header
  h1
    | Tickets Pending Approval

= render 'index_table', tickets: @tickets_pending_approval

h3 Approved Tickets

= render 'index_table', tickets: @tickets_approved

app/views/admin/approval/show.html.slim
.page-header
  h1
    | Ticket #
    = ticket.number

/ Job
dl.dl-horizontal
  dt Bill To:
  dd = ticket.bill_to_pretty

  dt Crew Chief:
  dd = ticket.crew_chief
  
/ Employees
hr

dl.dl-horizontal
  dt Employees:
  dd = partial 'table_employees_approval'

/ Mills
hr

dl.dl-horizontal
  dt Mills:
  dd = partial 'table_mills_approval'
  
/ Other Vehicles
hr

dl.dl-horizontal
  dt Trucks:
  dd = partial 'table_nonmills_approval'

/ Dimensions
hr

dl.dl-horizontal
  dt Depth:
  dd = ticket.milling_depth
  dt Width:
  dd = ticket.milling_depth
  dt Length:
  dd = ticket.milling_depth
  dt Area:
  dd = ticket.milling_square_yards

/ Supplies
hr

dl.dl-horizontal
  - if ticket.supplies_teeth.present?
    dt Teeth:
    dd = ticket.supplies_teeth

  - if ticket.supplies_holders.present?
    dt Holders:
    dd = ticket.supplies_holders

  - if ticket.supplies_oil.present?
    dt Oil:
    dd = ticket.supplies_oil

  - if ticket.supplies_notes.present?
    dt Supplies Notes:
    dd = ticket.delays_other_pretty

  - if ticket.supplies_teeth.blank? and ticket.supplies_holders.blank? and ticket.supplies_oil.blank? and ticket.supplies_notes.blank?
    dt Supplies:
    dd None

/ Delays
hr

dl.dl-horizontal
  - if ticket.delays_trucks.present?
    dt Truck Delays:
    dd = ticket.delays_trucks_pretty

  - if ticket.delays_paving.present?
    dt Paving Delays:
    dd = ticket.delays_paving_pretty

  - if ticket.delays_mot.present?
    dt MOT Delays:
    dd = ticket.delays_mot_pretty

  - if ticket.delays_other.present?
    dt Other Delays:
    dd = ticket.delays_other_pretty
  
  dt Total Delays:
  dd
    - if ticket.delays_total.present?
      strong
        = ticket.delays_total
    - else
      | None

  - if ticket.delays_notes.present?
    dt Notes:
    dd = ticket.delays_notes
  

/ Notes
hr

dl.dl-horizontal
  dt Notes:
  - if ticket.notes.blank?
    dd None
  - else
    dd
      .table-responsive
        table.table.table-striped
          tbody
            - ticket.notes.decorate.each do | note |
              tr
                td
                  = note.note
                  br
                  br
                  em = note.attribution
    
/ Customer Approval
hr

dl.dl-horizontal
  dt Customer Approval:
  - if ticket.pending_approval?
    dd Not yet approved
  - else
    dd = ticket.approval
  
    dt Customer Feedback:
    dd
      - if ticket.approval_feedback
        = ticket.approval_feedback
      - else
        | None
        
    dt = "#{ticket.approval} By:"
    dd
      = ticket.approval_name_and_title
      br
      = ticket.approval_email

    dt Signature
    dd
      img src="#{ticket.approval_signature}"

/ Finalization
hr

dl.dl-horizontal
  dt Finalized At:
  dd = ticket.finalized_at
  
hr

div#approval_form

  - if ticket.admin_approved?

    h2 This ticket has been approved.
  
  - else
  
    h2 Approve Ticket
  
    p.question When you approve this ticket, employee hours will be sent to payroll.
  
    = link_to 'Approve Ticket', admin_approval_approve_path(ticket), class: 'btn-approve', method: :patch
  
    = link_to 'Make Changes', ticket_employees_path(ticket), class: 'btn-disapprove'