config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :employees
  
  namespace :reports do
    get 'payroll' => 'payroll#show'
  end
  
  scope module: 'ticket' do
    get 'tickets/finalized' => 'tickets#index_finalized'
    resources :tickets do
      
      get 'job' => 'job#index'
      patch 'job' => 'job#update'

      get 'crew-chief' => 'job#index_crew_chief'
      patch 'crew-chief' => 'job#update'
      
      get 'employees' => 'employees#index'
      get 'employees/add' => 'employees#new'
      post 'employees/add' => 'employees#create'
      get 'employees/:employee_id' => 'employees#show', as: :employee_log
      patch 'employees/:employee_id/per-diem' => 'employees#per_diem_toggle', as: :employee_per_diem
      #post 'employees/:employee_id/:status' => 'employees#create_status', as: :employee_new_status
      post 'employees/status' => 'employees#create_status', as: :employee_new_status
      get 'employees/:employee_id/edit/:employee_entry_id' => 'employees#edit_status', as: :employee_edit_status
      patch 'employees/:employee_id/edit/:employee_entry_id' => 'employees#update_status'
      delete 'employees/:employee_id/edit/:employee_entry_id' => 'employees#delete_status'

      get 'vehicles' => 'vehicles#index'
      get 'vehicles/add' => 'vehicles#new'
      post 'vehicles/add' => 'vehicles#create'
      get 'vehicles/:vehicle_id' => 'vehicles#show', as: :vehicle_log
      get 'vehicles/:vehicle_id/inspection' => 'vehicles#display_inspection_form', as: :inspection_form
      get 'vehicles/:vehicle_id/refuel' => 'vehicles#new_refuel', as: :vehicle_refuel
      post 'vehicles/:vehicle_id/refuel' => 'vehicles#create_refuel'
      #post 'vehicles/:vehicle_id/:status' => 'vehicles#create_status', as: :vehicle_new_status
      post 'vehicles/status' => 'vehicles#create_status', as: :vehicle_new_status
      get 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#edit_status', as: :vehicle_edit_status
      patch 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#update_status'
      delete 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#delete_status'
      
      get 'dimensions' => 'dimensions#index'
      patch 'dimensions' => 'dimensions#update'
      
      get 'supplies' => 'supplies#index'
      patch 'supplies' => 'supplies#update'
      
      get 'delays' => 'delays#index'
      patch 'delays' => 'delays#update'
      
      get 'notes' => 'notes#index'
      get 'notes/add' => 'notes#new'
      post 'notes' => 'notes#create'
      
      get 'approval' => 'approval#index'
      get 'approval/:decision' => 'approval#approval_confirm', as: :approval_confirm
      patch 'approval/:decision' => 'approval#update'
      
      
      get 'finalize' => 'finalize#index'
      patch 'finalize' => 'finalize#update'
      
      collection do
        get :autocomplete_job_display_name
        
        get :autocomplete_vehicle_display_name
        
        #get :autocomplete_employee_display_name
        
        get 'autocomplete_crew_chief_display_name' => 'job#autocomplete_employee_display_name'
        
        get 'autocomplete_worker_display_name' => 'employees#autocomplete_employee_display_name'
      end
    end
  end

  
  namespace :admin do
    resources :payroll
    post 'payroll/calculate' => 'payroll#add_pending_tickets', as: :payroll_calculate
    resources :customers
    resources :employees
    resources :vehicles
    resources :jobs do
      get :autocomplete_customer_name, on: :collection
    end
    
    get 'approval/approved' => 'approval#index_approved'
    resources :approval do
      patch :approve
    end
  end
  
  root 'application#homepage'

end

app/controllers/admin/payroll_controller.rb
class Admin::PayrollController < ApplicationController
  before_action :set_payroll_period, only: [:show]
  
  def index
    @payroll_periods = PayrollPeriod.all
    
    @pending_tickets = PayrollPeriod.available_tickets
  end

  def show
    @entries = @payroll_period.summarized_entries
    @per_diems = @payroll_period.per_diems
    #raise @payroll_period.valid_entries.unscoped.inspect
  end
  
  def add_pending_tickets
    pp = PayrollPeriod.new
    pp.autoselect_all_possible_entries!
    pp.calculate!
    redirect_to admin_payroll_path(pp)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payroll_period
      @payroll_period = PayrollPeriod.find(params[:id])
    end
end

app/controllers/reports/payroll_controller.rb
require 'fx_datetime'

class Reports::PayrollController < ApplicationController
  def show
    
    
    @start = params[:start]
    @end = params[:end]
    if @start.blank?
      @start = '6 days ago'
    end
    if @end.blank?
      @end = 'today'
    end
    @start = @start.to_time_with_chronic
    @end = @end.to_time_with_chronic

    # TODO: Times inserted into SQL seem off. Fix this...

    @start.change(hour: 0, min: 0)
    @end.change(hour: 23, min: 59, sec: 59)
    
      
    @employees = {}
    @employee_entries = EmployeeEntry.where(time: @start..@end).where.not(status: 'idle')
    
    @employee_entries.each do |entry|
      @employees[entry.employee_id] ||= {
        name: entry.employee.to_s,
        duration_day: 0,
        duration_night: 0,
        duration_total: 0
      }
      
      if entry.duration_total and (entry.duration_total > 0)
        @employees[entry.employee_id][:duration_day] += entry.duration_day
        @employees[entry.employee_id][:duration_night] += entry.duration_night
        @employees[entry.employee_id][:duration_total] += entry.duration_total
      end
        
    end
    
  end
end

app/helpers/admin/payroll_helper.rb
module Admin::PayrollHelper
end

app/helpers/reports/payroll_helper.rb
module Reports::PayrollHelper
end

app/views/admin/payroll/index.html.slim
.page-header
  - if @pending_tickets.count > 0
    = link_to admin_payroll_calculate_path, class: 'btn btn-warning', method: :post do 
      span.glyphicon.glyphicon-plus
      |  Add 
      = pluralize @pending_tickets.count, 'Ticket'
      |  to a Payroll Period
  h1
    | Payroll Reports

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th
          | Dates
    tbody
      - @payroll_periods.each do | period |
        tr data-link="#{admin_payroll_path(period)}"
          td
            = period.start_date
            |  – 
            = period.end_date

app/views/admin/payroll/show.html.slim
.page-header
  h1
    | Pay Period 
    = @payroll_period.start_date
    |  through 
    = @payroll_period.end_date

.table-responsive
  table.table.table-striped
    thead
      tr
        th Employee
        th Bill To
        th Status
        th Pay Rate
        th Regular Time
        th Overtime
    tbody
      - @entries.each do |entry|
        - entry = entry.decorate
        - pr = entry.decoded_payroll
        tr
          td
            strong = pr.employee
          td = pr.ticket.decorate.bill_to_pretty
          td = pr.payroll_status_i18n
          td = pr.payroll_pay_rate_i18n
          td
            strong = entry.duration_standard
          td
            strong = entry.duration_overtime
            
- if @per_diems.present?
  hr

  h2 Per Diem Allowances

  .table-responsive
    table.table.table-striped
      thead
        tr
          th Employee
          th Days of Per Diem
          th Dollar Amount
      tbody
        - @per_diems.each do | employee_id, hash |
          tr
            td
              strong = hash[:name]
            td
              = hash[:count]
            td
              = number_to_currency(hash[:count] * PayrollPeriod::PER_DIEM_ALLOWANCE)