config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :employees
  
  namespace :reports do
    get 'payroll' => 'payroll#show'
  end
  
  scope module: 'ticket' do
    get 'tickets/finalized' => 'tickets#index_finalized'
    resources :tickets do
      
      get 'job' => 'job#index'
      patch 'job' => 'job#update'

      get 'crew-chief' => 'job#index_crew_chief'
      patch 'crew-chief' => 'job#update'
      
      get 'employees' => 'employees#index'
      get 'employees/add' => 'employees#new'
      post 'employees/add' => 'employees#create'
      get 'employees/:employee_id' => 'employees#show', as: :employee_log
      patch 'employees/:employee_id/per-diem' => 'employees#per_diem_toggle', as: :employee_per_diem
      #post 'employees/:employee_id/:status' => 'employees#create_status', as: :employee_new_status
      post 'employees/status' => 'employees#create_status', as: :employee_new_status
      get 'employees/:employee_id/edit/:employee_entry_id' => 'employees#edit_status', as: :employee_edit_status
      patch 'employees/:employee_id/edit/:employee_entry_id' => 'employees#update_status'
      delete 'employees/:employee_id/edit/:employee_entry_id' => 'employees#delete_status'

      get 'vehicles' => 'vehicles#index'
      get 'vehicles/add' => 'vehicles#new'
      post 'vehicles/add' => 'vehicles#create'
      get 'vehicles/:vehicle_id' => 'vehicles#show', as: :vehicle_log
      get 'vehicles/:vehicle_id/inspection' => 'vehicles#display_inspection_form', as: :inspection_form
      get 'vehicles/:vehicle_id/refuel' => 'vehicles#new_refuel', as: :vehicle_refuel
      post 'vehicles/:vehicle_id/refuel' => 'vehicles#create_refuel'
      #post 'vehicles/:vehicle_id/:status' => 'vehicles#create_status', as: :vehicle_new_status
      post 'vehicles/status' => 'vehicles#create_status', as: :vehicle_new_status
      get 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#edit_status', as: :vehicle_edit_status
      patch 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#update_status'
      delete 'vehicles/:vehicle_id/edit/:vehicle_entry_id' => 'vehicles#delete_status'
      
      get 'dimensions' => 'dimensions#index'
      patch 'dimensions' => 'dimensions#update'
      
      get 'supplies' => 'supplies#index'
      patch 'supplies' => 'supplies#update'
      
      get 'delays' => 'delays#index'
      patch 'delays' => 'delays#update'
      
      get 'notes' => 'notes#index'
      get 'notes/add' => 'notes#new'
      post 'notes' => 'notes#create'
      
      get 'approval' => 'approval#index'
      get 'approval/:decision' => 'approval#approval_confirm', as: :approval_confirm
      patch 'approval/:decision' => 'approval#update'
      
      
      get 'finalize' => 'finalize#index'
      patch 'finalize' => 'finalize#update'
      
      collection do
        get :autocomplete_job_display_name
        
        get :autocomplete_vehicle_display_name
        
        #get :autocomplete_employee_display_name
        
        get 'autocomplete_crew_chief_display_name' => 'job#autocomplete_employee_display_name'
        
        get 'autocomplete_worker_display_name' => 'employees#autocomplete_employee_display_name'
      end
    end
  end

  
  namespace :admin do
    resources :payroll
    post 'payroll/calculate' => 'payroll#add_pending_tickets', as: :payroll_calculate
    resources :customers
    resources :employees
    resources :vehicles
    resources :jobs do
      get :autocomplete_customer_name, on: :collection
    end
    
    get 'approval/approved' => 'approval#index_approved'
    resources :approval do
      patch :approve
    end
  end
  
  root 'application#homepage'

end

app/models/job.rb
class Job < ActiveRecord::Base
  include CreatedBy
  include DisplayName
  
  acts_as_paranoid
  
  belongs_to :customer
  has_many :tickets, class_name: 'Ticket::Ticket'
  has_many :employees, through: :tickets, class_name: 'Ticket::Employee'
  has_many :vehicles, through: :tickets, class_name: 'Ticket::Vehicle'
    
  enum billing: { milled_area: 1, day: 2, hour: 3 }
  enum pay_rate: { day_pay: 1, night_pay: 2 }
  
  scope :in_progress, -> { where(completed_at: nil) }
  scope :completed, -> { where.not(completed_at: nil) }
  
  # Don’t allow a Job to be created if we don’t know how to bill it.
  validates :customer, presence: true
  validates :billing, presence: true
  validates :internal_number, presence: true, uniqueness: true
  validates :customer_name, presence: true
  validates :pay_rate, presence: true
  
  # When customer_name is set, find or create a customer by that name
  def customer_name=(name)
    self.customer = Customer.find_or_create_by(name: name)
  end
  
  # Acme Construction
  def customer_name
    if customer
      customer.name
    end
  end
  
  # #23 - Acme Construction
  def to_s
    "##{internal_number} — #{customer_name}"
  end
  
  def completed?
    completed_at.present?
  end
  
  def complete!
    update(completed_at: Time.now)
  end
  
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  autocomplete :customer, :name, full: true, limit: 50

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    # authorize(Job)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_job_path(@job), notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if @job.update(job_params)
      redirect_to admin_job_path(@job), notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    redirect_to admin_jobs_path, notice: 'Job was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:internal_number, :customer_number, :billing, :completed, :customer_name, :pay_rate)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  autocomplete :customer, :name, full: true, limit: 50

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    # authorize(Job)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:internal_number, :customers_number, :flat_rate, :completed, :customer_name)
    end
end

app/controllers/ticket/job_controller.rb
class Ticket::JobController < Ticket::BaseController
  before_action :set_ticket, except: :autocomplete_employee_display_name
  
  autocomplete :employee, :display_name, limit: 50, full: true, scopes: [:crew_chief]
  
  def index_crew_chief
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/ticket/job_helper.rb
module Ticket::JobHelper
end

app/views/admin/jobs/_form.html.slim
- if @job.id
  - url = admin_job_path @job
- else
  - url = admin_jobs_path

= simple_form_for @job, url: url do |f|
  = partial 'error_notification', f: f

  .form-inputs
  
    = f.input :customer_name, as: :autocomplete, url: autocomplete_customer_name_admin_jobs_path, input_html: { data: { 'auto-focus' => true } }

    = f.input :internal_number
    
    = f.input :customer_number
        
    = f.input :billing, as: :button_radio

    = f.input :pay_rate, as: :button_radio
                  
  = partial 'autoshow_form_buttons', f: f

app/views/admin/jobs/edit.html.slim
.page-header
  = link_to admin_jobs_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to admin_job_path(@job), class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing Job

= render 'form'

app/views/admin/jobs/index.html.slim
= title 'Jobs'

.page-header
  = link_to new_admin_job_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Job
  h1
    | Jobs

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th
          | Customer
        th
          | BRM #
        th
          | Customer’s Job #
        th
          | Billing
        th
          | Completed
    tbody
      - @jobs.each do | job |
        tr data-link="#{admin_job_path(job)}"
          td
            = job.customer
          td
            = job.internal_number
          td
            = job.customer_number
          td
            = job.billing
          td
            = job.completed_at

app/views/admin/jobs/show.html.slim
.page-header
  = link_to admin_jobs_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to admin_job_path(@job), method: :delete, data: { confirm: @job.flash(:confirm_destroy) }, class: 'btn-delete' do
    span.glyphicon.glyphicon-remove
    |  Delete
  = link_to edit_admin_job_path(@job), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Job
dl.dl-horizontal
  = show_model_data @job, :customer
  = show_model_data @job, :internal_number
  = show_model_data @job, :customer_number
  = show_model_data @job, :billing
  = show_model_data @job, :pay_rate
  = show_model_data @job, :completed_at
hr